# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MKYoutubeMp3DownloaderExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MKYoutubeMp3DownloaderExample
   pod 'MKYoutubeMp3Downloader', :path => '~/Documents/Workspace/iOS/libraries/MKYoutubeMp3Downloader'
end
