# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    pod 'MKYoutubeMp3Downloader', :path => '../../MKYoutubeMp3Downloader'
end

target 'MKYoutubeMp3DownloaderExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  shared_pods
end

target 'MKYoutubeMp3DownloaderExampleShare' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_modular_headers!
  shared_pods
end
